# Generated by Django 3.2.5 on 2022-08-02 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='discont_price',
            new_name='discount_price',
        ),
    ]
