# Generated by Django 3.2.5 on 2022-08-05 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_product_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='user_name',
        ),
    ]
